BASIC Pytorch

In [32]:
import torch
import torch.nn as nn

In [3]:
example_tensor = torch.tensor([[1,2],[3,4]])

In [8]:
example_tensor.device

device(type='cpu')

In [9]:
example_tensor.shape

torch.Size([2, 2])

In [11]:
#to get rank, and no. of element
print('rank', len(example_tensor.shape))
print('no. of element', example_tensor.numel())

rank 2
no. of element 4


In [13]:
# getting column and rows.
first_row  = example_tensor[0,:]
first_column = example_tensor[:,0]
first_row,first_column

(tensor([1, 2]), tensor([1, 3]))

In [14]:
example_tensor

tensor([[1, 2],
        [3, 4]])

In [16]:
example_tensor//2 # applies broadcasting :)

tensor([[0, 1],
        [1, 2]])

In [21]:
a = torch.randn(example_tensor.shape)

In [22]:
a

tensor([[1.5198, 0.6477],
        [0.7127, 0.1257]])

In [24]:
a.mean(dim=1)

tensor([1.0837, 0.4192])

In [31]:
a.mean(dim=0)

tensor([1.1163, 0.3867])

In [35]:
# working with nn module
# nn.Linear performs Ax+b, note: a,x dimensions should match as per matrix multiplicaton property
linear = nn.Linear(10,2) # take nx10 input size and outputs nx2 shape data.
example = torch.randn(3,10)
print('before',example)
example = linear(example)
example

before tensor([[-0.2064, -1.1983,  1.0940, -1.9076, -0.9360,  1.3513,  0.0791,  2.1765,
          0.0427,  0.0271],
        [ 0.4900, -0.9306, -0.0106, -0.4529, -1.5940, -0.2319,  0.5281,  0.9652,
          0.0851,  1.9323],
        [-0.8620,  0.8580, -0.0613, -0.7515,  0.1324, -0.1783, -0.0952,  0.4113,
          2.0565,  0.8771]])


tensor([[-0.3426, -0.1449],
        [ 0.4541, -0.4305],
        [-0.8054, -0.0408]], grad_fn=<AddmmBackward>)

In [37]:
# nn.Relu sets in general all negative terms goes 0.
relu = nn.ReLU()
rel_output = relu(example)
rel_output

tensor([[0.0000, 0.0000],
        [0.4541, 0.0000],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [41]:
# nn.BatchNorm1d rescales the batch of n inputs to have consistent mean and standard deviation
btch  = nn.BatchNorm1d(2) # takes size of input dimenstions.
btch_output = btch(example)
btch_output



tensor([[-0.2139,  0.3673],
        [ 1.3176, -1.3661],
        [-1.1037,  0.9988]], grad_fn=<NativeBatchNormBackward>)

In [48]:
# nn.Sequential used to perform all operation at once!
test_data = torch.randn(2,2) + 1

logistic_reg = nn.Sequential(
    nn.Linear(2,1),
    nn.BatchNorm1d(1), # note: dimension should be output of linear that is nx1 here
    nn.ReLU()
)

print(test_data)
logistic_reg(test_data)


tensor([[ 0.0036, -0.0046],
        [ 2.6728,  1.5010]])


tensor([[1.0000],
        [0.0000]], grad_fn=<ReluBackward0>)

In [56]:
list(logistic_reg.parameters()) # we can access the parameters like this..

[Parameter containing:
 tensor([[-0.3300, -0.5779]], requires_grad=True),
 Parameter containing:
 tensor([-0.5638], requires_grad=True),
 Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]

In [57]:
# automatic calculation of gradient using torch.optim module.
import torch.optim as optim
adam = optim.Adam(logistic_reg.parameters(),lr=1e-3)

In [58]:
#training loop

train_example = torch.randn(5,5) + 1


architecture = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

#optimizer
adam = optim.Adam(architecture.parameters(),lr=1e-2)

for i in range(5):
    adam.zero_grad()
    curr_loss = torch.abs(1-architecture(train_example)).mean()
    curr_loss.backward()
    adam.step()
    print(curr_loss)

tensor(0.8252, grad_fn=<MeanBackward0>)
tensor(0.7988, grad_fn=<MeanBackward0>)
tensor(0.7720, grad_fn=<MeanBackward0>)
tensor(0.7450, grad_fn=<MeanBackward0>)
tensor(0.7177, grad_fn=<MeanBackward0>)
